loop: single

model_folder: ./models
uv_path: ./assets/base.obj
uv_mask_path: ./assets/uv_mask.png
base_pose: ./assets/poses/base_pose.npy
model_type: smplx
output_path: ./output/
gender: male # from [male, female, neutral]
CLIP: ViT-B/32

render: diffuse # from [diffuse, pbr, normal, tangent]
gpu: 0

seed: 42
render_res: 256
texture_res: 256
rand_bkg: true
rand_pose: false
debug_log: true

epochs: 1000
log_int: 20
batch_size: 60
shape_lr: 0.01
texture_lr: 0.01
displacement_lr: 0.0001
TV_weight: 0.000001

blur: true
kernel_size:
- 1
- 1
blur_sigma:
- 1
- 1

betas: 10
expressions: 10

optim: # from [body, expression, texture, normal, specular, pose, displacement]
- body
- expression
- texture
- normal
- specular

options: # from [face, full, back]
- face
- full
- back

face_text: a fat 3D rendering of the face of a Sumo Wrestler
full_text: a fat 3D rendering of a Sumo Wrestler
back_text: a fat 3D rendering of the back of a Sumo Wrestler

cameras:
  back:
    azim:
    - 250.0
    - 290.0
    dist:
    - 1.3
    - 1.3
    elev:
    - 20.0
    - 20.0
    fov:
    - 90.0
    - 90.0
    offset:
    - 0.0
    - 0.15
    - 0.0
  face:
    azim:
    - 50.0
    - 120.0
    dist:
    - 1.2
    - 1.2
    elev:
    - 40.0
    - 60.0
    fov:
    - 20.0
    - 90.0
    offset:
    - 0.025
    - 0.85
    - 0.0
  full:
    azim:
    - 50.0
    - 120.0
    dist:
    - 1.3
    - 2.0
    elev:
    - 0.0
    - 20.0
    fov:
    - 20.0
    - 90.0
    offset:
    - 0.0
    - 0.15
    - 0.0